/* eslint-disable @typescript-eslint/no-explicit-any -- Ticket #104: Dynamic workflow node execution and field mapping */
import { NodeExecutionStrategy, ExecutionContext } from './NodeStrategy.js';
import { generateWithRetry } from '../services/RetryService.js';

export class ReviewerNodeStrategy implements NodeExecutionStrategy {
  async execute(node: any, context: ExecutionContext): Promise<void> {
    const criteria = node.fields.criteria || "";
    const maxIterations = Math.max(1, Number(node.fields.maxIterations) || 1);
    const reviewTargetText = typeof context.localValue === 'string' ? context.localValue : JSON.stringify(context.localValue);

    const isSandbox = !context.apiKey || context.apiKey === "sandbox_free_test_gemini" || context.apiKey === "your_gemini_api_key_here";
    let runText = reviewTargetText;
    let iteration = 0;
    let critiqueResponse = "";
    let passed = false;

    if (isSandbox) {
      iteration = 1;
      passed = true;
      critiqueResponse = "PASS: Output meets all criteria perfectly under simulated audit environment.";
    } else {
      while (iteration < maxIterations && !passed) {
        iteration++;
        const reviewerPrompt = `Analyze the following content generated by our coding unit against these strict quality requirements:
Requirements: "${criteria}"

Content to analyze:
\`\`\`
${runText}
\`\`\`

If it perfectly matches, output exactly "PASS".
If it fails any criteria, explain details & write exactly "FAIL [explanation]", then outline the precise suggestions for correct output.`;

        const { response } = await generateWithRetry(
          context.ai,
          'gemini-3.5-flash',
          reviewerPrompt,
          {
            temperature: 0.1,
            systemInstruction: "You are an automated strict unit testing system and layout auditor."
          }
        );

        critiqueResponse = response.text || "";
        if (critiqueResponse.trim().startsWith("PASS")) {
          passed = true;
          break;
        } else {
          const correctionPrompt = `A code/text critique was returned:
Critic critique: ${critiqueResponse}

Please regenerate the output from scratch, integrating all criticisms. Maintain high standards. No introductions, only the final polished code.`;

          const { response: correctionRes } = await generateWithRetry(
            context.ai,
            'gemini-3.5-flash',
            `${reviewTargetText}\n\n${correctionPrompt}`,
            {
              temperature: 0.2,
              systemInstruction: "You are a self-healing master developer unit."
            }
          );
          runText = correctionRes.text || "";
        }
      }
    }

    context.nodeOutputs[node.id] = runText;
    context.activeValueReference.value = runText;
    context.iterationsCount[node.id] = (context.iterationsCount[node.id] || 0) + iteration;

    context.logs.push({
      nodeId: node.id,
      nodeTitle: node.title,
      status: 'completed',
      input: `Criteria: ${criteria}`,
      output: passed 
        ? `Passed audit successfully after ${iteration} iterations!\n\n${critiqueResponse}` 
        : `Audit completed maximum cycles (${iteration}). Output refined iteratively with critique:\n\n${critiqueResponse}`,
      iterationCount: iteration,
      duration: Date.now() - context.stepStart
    });
  }
}
