import { LLMProvider } from './providers.js';

/**
 * 1. MULTI-AGENT SYNERGY PATTERNS (Supervisor & Swarm Engines)
 */
export interface AgentSpec {
  name: string;
  role: string;
  systemInstruction: string;
}

export class AgentSwarmTeam {
  private supervisor: AgentSpec;
  private specialists: AgentSpec[];
  private provider: LLMProvider;

  constructor(provider: LLMProvider, supervisor: AgentSpec, specialists: AgentSpec[]) {
    this.provider = provider;
    this.supervisor = supervisor;
    this.specialists = specialists;
  }

  /**
   * Supervisor dispatches complex customer request to dedicated agent units,
   * then aggregates their separate findings into a master solution.
   */
  async delegateAndExecute(task: string): Promise<string> {
    // 1. Ask supervisor which specialist agent fits best
    const specialistsDesc = this.specialists
      .map(s => `Agent: ${s.name} | Role: ${s.role} | System Instructions: ${s.systemInstruction}`)
      .join("\n");

    const supervisorPrompt = `You are the Lead Coordinator: ${this.supervisor.name}.
Your job is to read the user task and delegate it to the single best specialist agent from this team:
${specialistsDesc}

Task: "${task}"

Select the perfect agent and output their exact name first, followed by specific instructions for them.
Format your answer exactly like:
DELEGATE: <AgentName>
INSTRUCTIONS: <Specific task constraints>`;

    const supervisorResult = await this.provider.generate(supervisorPrompt);
    const text = supervisorResult.text || "";

    // 2. Parse selector
    const delegateMatch = text.match(/DELEGATE:\s*(\w+)/i);
    const instructionsMatch = text.match(/INSTRUCTIONS:\s*([\s\S]+)/i);

    const selectedName = delegateMatch ? delegateMatch[1].trim() : this.specialists[0].name;
    const specialistInstructions = instructionsMatch ? instructionsMatch[1].trim() : task;

    const specialist = this.specialists.find(s => s.name.toLowerCase() === selectedName.toLowerCase()) || this.specialists[0];

    // 3. Execute specialist model call
    const executionResult = await this.provider.generate(specialistInstructions, {
      systemInstruction: specialist.systemInstruction
    });

    const specialistText = executionResult.text || "";

    // 4. Conclude and wrap via supervisor
    const synthesisPrompt = `You are the lead supervisor. Re-verify, polish, and output the final synthesis based on your specialist's work.
Specialist (${specialist.name}) output:
"""
${specialistText}
"""`;

    const finalResult = await this.provider.generate(synthesisPrompt, {
      systemInstruction: this.supervisor.systemInstruction
    });

    return finalResult.text || specialistText;
  }
}

/**
 * 2. RETRIEVAL-AUGMENTED GENERATION (RAG) PIPELINE
 */
export interface DocumentChunk {
  id: string;
  text: string;
  sourceFile: string;
}

export class IngestionRAGEngine {
  private chunksStore: DocumentChunk[] = [];

  constructor() {}

  /**
   * Splits arbitrary Markdown or PDF text arrays into token-bounded semantic elements
   */
  chunkDocument(rawText: string, fileName: string, chunkSize: number = 200, overlap: number = 40): DocumentChunk[] {
    const words = rawText.split(/\s+/);
    const chunks: DocumentChunk[] = [];
    let idx = 0;

    while (idx < words.length) {
      const chunkWords = words.slice(idx, idx + chunkSize);
      const text = chunkWords.join(" ");
      chunks.push({
        id: `chunk_${fileName}_${Math.random().toString(36).substr(2, 5)}`,
        text,
        sourceFile: fileName
      });
      idx += (chunkSize - overlap);
    }

    this.chunksStore.push(...chunks);
    return chunks;
  }

  /**
   * Simple TF-IDF/BM25 style matching search for clean static deployments
   */
  async searchWorkspaceRAG(query: string, limit: number = 3): Promise<DocumentChunk[]> {
    const queryTerms = query.toLowerCase().split(/\s+/);
    
    // Evaluate terms overlap frequency
    const itemScores = this.chunksStore.map(chunk => {
      let score = 0;
      const lowerText = chunk.text.toLowerCase();
      queryTerms.forEach(t => {
        if (lowerText.includes(t)) {
          score += 1.0;
        }
      });
      return { chunk, score };
    });

    return itemScores
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map(entry => entry.chunk);
  }
}

/**
 * 3. PRODUCTION-GRADE EVALS (LLM-As-A-Judge Metric Evaluator)
 */
export interface EvaluationReport {
  score: number; // 0.0 to 1.0
  justification: string;
  recommendations: string[];
}

export class LLMJudgeEvaluator {
  private provider: LLMProvider;

  constructor(provider: LLMProvider) {
    this.provider = provider;
  }

  /**
   * Evaluates the output generated by our workflow against raw user query & correct reference groundings
   */
  async evaluateOutput(query: string, output: string, groundTruth: string): Promise<EvaluationReport> {
    const evalPrompt = `Your job is to audit and grade an agent system output response against a ground truth answer.
User Inquiry: "${query}"
Agent Response:
"""
${output}
"""

Expected Ground Truth:
"""
${groundTruth}
"""

Evaluate across three metric coordinates:
1. Accuracy: Is facts completely aligned with ground truth?
2. Helpful scope: Does it answers all user queries directly?
3. Redundancy: Are there conversational introductions or filler sentences?

You must answer using valid JSON format ONLY:
{
  "score": <number between 0.0 and 1.0 reflecting compliance>,
  "justification": "<Your logical audit detail reasons explaining why the grade was chosen>",
  "recommendations": ["Recommendation 1", "Recommendation 2"]
}`;

    const judgeCall = await this.provider.generate(evalPrompt, {
      temperature: 0.0, // strictly deterministic evaluation
      systemInstruction: "You are an objective metric judge. Always return valid, compliant JSON blocks."
    });

    try {
      const cleanJson = (judgeCall.text || "").replace(/```json|```/g, "").trim();
      return JSON.parse(cleanJson);
    } catch {
      return {
        score: 0.5,
        justification: "Failed to parse judge output structure to valid schema format. Raw: " + (judgeCall.text || ""),
        recommendations: ["Review text parse format constraints."]
      };
    }
  }
}

/**
 * 4. HUMAN-IN-THE-LOOP BREAKPOINTS CONTROL
 */
export interface BreakpointInterrupt {
  nodeId: string;
  status: 'paused' | 'approved' | 'rejected';
  promptData: string;
  approvedValue?: string;
}

export class BreakpointsManager {
  private activeBreakpoints: Map<string, BreakpointInterrupt> = new Map();

  registerBreakpoint(nodeId: string, promptData: string) {
    this.activeBreakpoints.set(nodeId, {
      nodeId,
      status: 'paused',
      promptData
    });
  }

  approveBreakpoint(nodeId: string, value?: string) {
    const bpt = this.activeBreakpoints.get(nodeId);
    if (bpt) {
      bpt.status = 'approved';
      bpt.approvedValue = value;
    }
  }

  rejectBreakpoint(nodeId: string) {
    const bpt = this.activeBreakpoints.get(nodeId);
    if (bpt) {
      bpt.status = 'rejected';
    }
  }

  getStatus(nodeId: string): BreakpointInterrupt['status'] | 'none' {
    return this.activeBreakpoints.get(nodeId)?.status || 'none';
  }
}
